### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by vidimus** [ColinBaumgartner/MOM-Scenarios#1]
Hello, @ColinBaumgartner 

One of my Spanish translation group wants to translate your scenario into Spanish. Can he do it? In case he can, are you available for updating your scenario with the translation?

**Comment by ColinBaumgartner** [comment]
Yes of course!  Just let me know once you’ve finished and I can update.

Colin

**Comment by vidimus** [comment]
> Yes of course! Just let me know once you’ve finished and I can update. Colin
> […](#)
Great, @ColinBaumgartner . I'm going to tell him to start the translation. Thanks.

**Comment by vidimus** [comment]
Hello, @ColinBaumgartner 

Translation has finished. Now we have to test it. I will contact you in the following days as soon as we end with the proof reading and the other reviewing stuff.

**Comment by ColinBaumgartner** [comment]
Sounds good!  Just let me know!

**Comment by vidimus** [comment]
Hello, @ColinBaumgartner 

File is ready. Here's the translation text file:

[Localization.Spanish.txt](https://github.com/ColinBaumgartner/MOM-Scenarios/files/5826277/Localization.Spanish.txt)

In case you don't know how to add the translation file to the scenario or you just don't want to take time doing it, here is the file with the Valkyrie package done:


[TheRitualScenario.zip](https://github.com/ColinBaumgartner/MOM-Scenarios/files/5826279/TheRitualScenario.zip)

Unzip and replace the old ones on your repository.

**Comment by vidimus** [comment]
Testing the scenario I found some issues.
<
<
<
-------------------------------SPOILER ALERT---------------------------------------------------------------------
<
<
<
<
<
<
<
<
- At the temple, there are two events that trigger the cultist twice and sometimes even after the pillar destruction (losing the girl on the right side of the temple when running, for example). 
- If your cultist are still alive when you reach the village back, there're not removed from the screen, and they remain on the end UI. 
- If the girl is recaptured by the cultists, there's no way to end the scenario.

**Comment by vidimus** [comment]
I see you updated the scenario with the Spanish translation, @ColinBaumgartner . Thanks!

**Comment by ColinBaumgartner** [comment]
Vidimus,

Certainly!  Thanks for taking the time to translate the scenario.  I haven’t had a minute yet to fix the bugs you mentioned, but I will definitely jump on that when I have a free moment.  

I’m working on another scenario that will be a lot bigger and will have more story & some new game dynamics.  I’m hoping it turns out as I imagine.  Maybe we can work on a translation of that as well eventually.

Thanks again!
Colin

**Comment by vidimus** [comment]
Sure, @ColinBaumgartner . Good luck with your new scenario. I will certainly play it!

**Comment by vidimus** [comment]
Hello, @ColinBaumgartner 

Here's an update of the Spanish translation, correcting some minor typos and spelling. Could you please update the scenario with the new translation version?

The Valkyrie package (just to replace the repo files): 
[TheRitualScenario.zip](https://github.com/ColinBaumgartner/MOM-Scenarios/files/5974572/TheRitualScenario.zip)

Or just the Localization text file
[Localization.Spanish.txt](https://github.com/ColinBaumgartner/MOM-Scenarios/files/5974573/Localization.Spanish.txt)

**Comment by vidimus** [comment]
Hello, @ColinBaumgartner 
Any news about updating the Spanish translation I posted on the previous message?

**Comment by ColinBaumgartner** [comment]
Thanks for reaching out again!  I missed your last message.  Update should be live now!

Cheers, 
Colin

**Comment by vidimus** [comment]
> Thanks for reaching out again! I missed your last message. Update should be live now! Cheers, Colin
> […]

Hello, @ColinBaumgartner 
Valkyrie shows no update for the scenario. Did you upload the files to your repository?

**Comment by ColinBaumgartner** [comment]
I’m not sure why that is.  I just uploaded the files again.  Should be the current version.

**Comment by vidimus** [comment]
Your repository files are still the old version ones. You need to upload them and confirm the replacement of the old ones (names are the same, so github will overwrite them). 

![Screenshot_2021-03-08-15-29-57-01](https://user-images.githubusercontent.com/41538948/110334600-3ec15380-8023-11eb-9870-64ff0fc779c8.jpg)

**Comment by ColinBaumgartner** [comment]
Hmmm.  Maybe my computer wasn’t pushing the changes to the server for some reason.  The repository is updated on my computer…. See if it is updated now.  Sorry about all these delays!

**Comment by vidimus** [comment]
Now it's. Thanks, @ColinBaumgartner
